services:

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=bdinf
      - DOCKER_INFLUXDB_INIT_PASSWORD=bdinfisawesome
      - DOCKER_INFLUXDB_INIT_ORG=bdinf-org
      - DOCKER_INFLUXDB_INIT_BUCKET=bdinf-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=14iJvsBJKp37nLXjIZvE4RbAoEO2dNs1k0GvCbKuJUnF_ub4pSWWw80O739jabLPMD-XBzA72WSX9f-4FuDBQ==
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - dbnet

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bdinf
      - MONGO_INITDB_ROOT_PASSWORD=bdinfisawesome
    volumes:
      - mongo_data:/data/db
    networks:
      - dbnet


  spark-master:
    build: .
    image: custom-spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8081:8080"

  spark-worker-1:
    build: .
    image: custom-spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
    ports:
      - "8082:8081"

  spark-worker-2:
    build: .
    image: custom-spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
    ports:
      - "8083:8081"

  spark-worker-3:
    build: .
    image: custom-spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
    ports:
      - "8084:8081"

  spark-worker-4:
    build: .
    image: custom-spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
    ports:
      - "8085:8081"


volumes:
  influxdb_data:
  mongo_data:

networks:
  dbnet:
    driver: bridge